code_task:
  description: >
    Tu vas créer une application en python en suivant ces instructions :
    
    Instructions
    ------------
    {app}
    
  expected_output: >
    Ta réponse finale sera le code python et uniquement le code python.

review_task:
  description: >
    En utilisant le code produit, vérifie que le code est complet et qu'il n'y a pas d'erreurs. Vérifie tout types d'erreur.

    Assure toi que la sécurité est maximale et si ce n'est pas le cas, demande des corrections.

    Tu t'assureras que le code est complet et qu'il effectue tout ce qu'il est supposé faire.

  expected_output: >

write_task:
  description: >
    Tu vas rédiger dans des fichiers python le code généré par le développeur et revu par l'ingénieur qualité.
    
  expected_output: >
    Ta réponse finale sera des fichiers python contenant le code produit.
    